config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :companies
  resources :characters
  resources :species
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "characters#index"
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :set_species, only: %i[ show edit update destroy ]

  # GET /species or /species.json
  def index
    @species = Species.all
  end

  # GET /species/1 or /species/1.json
  def show
  end

  # GET /species/new
  def new
    @species = Species.new
  end

  # GET /species/1/edit
  def edit
  end

  # POST /species or /species.json
  def create
    @species = Species.new(species_params)

    respond_to do |format|
      if @species.save
        format.html { redirect_to species_url(@species), notice: "Species was successfully created." }
        format.json { render :show, status: :created, location: @species }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /species/1 or /species/1.json
  def update
    respond_to do |format|
      if @species.update(species_params)
        format.html { redirect_to species_url(@species), notice: "Species was successfully updated." }
        format.json { render :show, status: :ok, location: @species }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1 or /species/1.json
  def destroy
    @species.destroy!

    respond_to do |format|
      format.html { redirect_to species_index_url, notice: "Species was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_species
      @species = Species.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def species_params
      params.require(:species).permit(:species_name)
    end
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/species/_form.html.erb
<%= form_with(model: species) do |form| %>
  <% if species.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(species.errors.count, "error") %> prohibited this species from being saved:</h2>

      <ul>
        <% species.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :species_name, style: "display: block" %>
    <%= form.text_field :species_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/species/_species.html.erb
<div id="<%= dom_id species %>">
  <p>
    <strong>Species name:</strong>
    <%= species.species_name %>
  </p>

</div>

app/views/species/edit.html.erb
<% content_for :title, "Editing species" %>

<h1>Editing species</h1>

<%= render "form", species: @species %>

<br>

<div>
  <%= link_to "Show this species", @species %> |
  <%= link_to "Back to species", species_index_path %>
</div>

app/views/species/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Species" %>

<h1>Species</h1>

<div id="species">
  <% @species.each do |species| %>
    <%= render species %>
    <p>
      <%= link_to "Show this species", species %>
    </p>
  <% end %>
</div>

<%= link_to "New species", new_species_path %>

app/views/species/new.html.erb
<% content_for :title, "New species" %>

<h1>New species</h1>

<%= render "form", species: @species %>

<br>

<div>
  <%= link_to "Back to species", species_index_path %>
</div>

app/views/species/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @species %>

<div>
  <%= link_to "Edit this species", edit_species_path(@species) %> |
  <%= link_to "Back to species", species_index_path %>

  <%= button_to "Destroy this species", @species, method: :delete %>
</div>