config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :companies
  resources :characters
  resources :species
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "characters#index"
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :species

  has_many :person_jobs, dependent: :destroy, foreign_key: :person_id
  has_many :jobs, through: :person_jobs
  has_many :companies, through: :jobs

  normalizes :first_name, :nick_name, :last_name, :given_name,
             with: ->(value) { value.strip }

  validates :first_name,
            uniqueness: { scope: :last_name,
                          message: "first_name and last_name already exists" }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :species, presence: true
  validates :gender, presence: true
  validates :gender, inclusion: { in: %w[male female] }
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]

  def index
    query = Character
            .includes(:species)
            .includes(person_jobs: { job: :company })
    if params[:column].present?
      # @characters = query.order("#{params[:column]}").all
      @characters = query.order("#{params[:column]} #{params[:direction]}").all
    else
      @characters = query.all
    end
  end

  def show
  end

  def new
    @character = Character.new
  end

  def edit
  end

  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to character_url(@character), notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to character_url(@character), notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @character.destroy!

    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character
                    .includes(species: [], person_jobs: { job: :company })
                    .where(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:nick_name, :first_name, :last_name, :given_name, :gender, :species_id)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
  # def sort_link(column:, label:)
  #   link_to(label, characters_path(column: column))
  # end

  # def sort_link(column:, label:)
  #   direction = column == params[:column] ? future_direction : 'asc'
  #   link_to(label, characters_path(column: column, direction: direction))
  # end

  # def future_direction = params[:direction] == 'asc' ? 'desc' : 'asc'

  # def sort_link(column:, label:)
  #   link_to(label, characters_path(column: column), data: { turbo_action: 'replace' })
  # end

  def sort_link(column:, label:)
    direction = column == params[:column] ? future_direction : 'asc'
    link_to(label, characters_path(column: column, direction: direction), data: { turbo_action: 'replace' })
  end

  def future_direction = params[:direction] == 'asc' ? 'desc' : 'asc'

  def sort_arrow
    case params[:direction]
    when 'asc' then tag.i(class: "bi bi-arrow-up")
    when 'desc' then tag.i(class: "bi bi-arrow-down")
    else tag.i(class: "bi bi-arrow-down-up")
    end
  end

  def sort_arrow_for(column)
    params[:column] == column ? sort_arrow : tag.i(class: "bi bi-arrow-down-up")
  end
end

app/views/characters/_character.html.erb
<div id="<%= dom_id character %>">
  <p>
    <strong>Nick name:</strong>
    <%= character.nick_name %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= character.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= character.last_name %>
  </p>

  <p>
    <strong>Given name:</strong>
    <%= character.given_name %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= character.gender %>
  </p>

  <p>
    <strong>Species:</strong>
    <%= character.species_id %>
  </p>

</div>

app/views/characters/_form.html.erb
<%= form_with(model: character) do |form| %>
  <% if character.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nick_name, style: "display: block" %>
    <%= form.text_field :nick_name %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :given_name, style: "display: block" %>
    <%= form.text_field :given_name %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :species_id, style: "display: block" %>
    <%= form.text_field :species_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<% content_for :title, "Editing character" %>

<h1>Editing character</h1>

<%= render "form", character: @character %>

<br>

<div>
  <%= link_to "Show this character", @character %> |
  <%= link_to "Back to characters", characters_path %>
</div>

app/views/characters/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Characters" %>
<div class="container text-center">

  <div class="row justify-content-start">
    <div class="col-9">
      <h1>Characters</h1>

      <table class="table table-striped table-hover">
        <thead class="sticky-top">
          <tr class="table-primary">
            <th scope="col">
              <%= sort_link(column: "id", label: "Id") %>
              <%= sort_arrow_for("id") %>
            </th>
            <th scope="col">
              <%= sort_link(column: "first_name", label: "First Name") %>
              <%= sort_arrow_for("first_name") %>
            </th>
            <th scope="col">
              <%= sort_link(column: "last_name", label: "Last Name") %>
              <%= sort_arrow_for("last_name") %>
            </th>
            <th scope="col">
              <%= sort_link(column: "gender", label: "Gender") %>
              <%= sort_arrow_for("gender") %>
            </th>
            <th scope="col">
              <%= sort_link(column: "species.species_name", label: "Species") %>
              <%= sort_arrow_for("species.species_name") %>
            </th>
            <th scope="col">
              Company-Job
            </th>
          </tr>
        </thead>

        <tbody class="scrollable-table">
          <div id="characters">
          <% @characters.each do |character| %>
            <tr id="<%= dom_id(character) %>">
              <th scope="row"><%= link_to "#{character.id}", edit_character_path(character) %></th>
              <td><%= character.first_name %></td>
              <td><%= character.last_name %></td>
              <td><%= character.gender %></td>
              <td><%= character.species.species_name %></td>
              <td class="text-start">
                <ul class="list-unstyled">
                  <% character.person_jobs.each do |person_job| %>
                    <li>
                      <b><%= person_job.job.company.company_name %></b><br>
                      &nbsp; - <%= person_job.job.role %><br>
                      &nbsp; &nbsp;
                      <em>
                        (<%= person_job.start_date.strftime("%e %b '%y") %> -
                         <%= person_job.end_date&.strftime("%e %b '%y") || 'present' %> )
                      </em>
                    </li>
                  <% end %>
                </ul>
              </td>
            </tr>
          <% end %>
          </div>
        </tbody>
      </table>
    </div>

    <div class="col-3">
      <%= link_to "New", new_character_path, class: "mt-5 sticky-top btn btn-primary" %>
    </div>
  </div>
</div>

app/views/characters/new.html.erb
<% content_for :title, "New character" %>

<h1>New character</h1>

<%= render "form", character: @character %>

<br>

<div>
  <%= link_to "Back to characters", characters_path %>
</div>

app/views/characters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @character %>

<div>
  <%= link_to "Edit this character", edit_character_path(@character) %> |
  <%= link_to "Back to characters", characters_path %>

  <%= button_to "Destroy this character", @character, method: :delete %>
</div>